server:
    port: 8888
    #context-path: #/liuzh/

logging:
    level:
        com.troylc.mybatis: DEBUG

spring:
    datasource:
#        url: jdbc:sqlserver://localhost:3407;DatabaseName=test
#        username: root
#        password: 
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        name: citydb
        url: jdbc:mysql://dmpmysql:3306/citydb?useUnicode=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8
        username: root
        password: talent
        # 使用druid数据源
        #com.alibaba.druid.pool.DruidDataSource
        # 使用hikari数据源
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        schema: city-db.sql
        data: city-data.sql
        continue-on-error: false
        initialize: true



#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
